### PR TITLE
Pull several updates from upstream for arm64 compatibility

### PR DESCRIPTION
**Pull request by AniLeo**

### CODE REVIEW

**Comment by AniLeo** [comment]
Needs 3rdparty/CMakeLists.txt update on RPCS3 side

**Comment by Megamouse** [comment]
This is removing all the encoders, decoders and muxers that we need for rpcs3, whilst adding the mjpeg2jpeg bitstream filter, that we don't use (At least I don't know what it's for).
It's probably better to remove the unnecessary filter and replace the encoder stuff:

image

```
+string(APPEND OPTIONS " --enable-encoder=pcm_s16le --enable-encoder=mp3 --enable-encoder=ac3 --enable-encoder=aac")
+string(APPEND OPTIONS " --enable-encoder=ffv1 --enable-encoder=mpeg4 --enable-encoder=mjpeg --enable-encoder=h264")
+string(APPEND OPTIONS " --enable-muxer=avi --enable-muxer=h264 --enable-muxer=mjpeg --enable-muxer=mp4")
```

Also note the "19" above. It has to be 19 if you remove the mjpeg2jpeg line

**Comment by Megamouse** [comment]
Why isn't this commit based on the vita3k/master branch?

**Comment by AniLeo** [comment]
> Why isn't this commit based on the vita3k/master branch?

Because the master branch squashed the entire git history, the `old` branch contains all the same commits but in an unsquashed manner. This is to avoid destroying git history and importing individual commits as is.

**Comment by AniLeo** [comment]
> This is removing all the encoders, decoders and muxers that we need for rpcs3, whilst adding the mjpeg2jpeg bitstream filter, that we don't use (At least I don't know what it's for).
> It's probably better to remove the unnecessary filter and replace the encoder stuff:

Nice catch, I restored the encoders on the .patch file

I didn't remove the other added filter as we don't lose anything in leaving one more filter enabled - there's probably several others in there that we don't use - and smaller modifications from upstream allows for easier maintenance/rebasing in the future

**Comment by Macdu** [comment]
> > Why isn't this commit based on the vita3k/master branch?
> 
> Because the master branch squashed the entire git history, the `old` branch contains all the same commits but in an unsquashed manner. This is to avoid destroying git history and importing individual commits as is.

Hello, the reason I squashed the entire git history together is to decrease the repository size when cloning it.
Right now if you do a `git clone https://github.com/RPCS3/ffmpeg-core.git`, the resulting repository size is around 250MB. This is because before the squash, the prebuilts for all the targets were in the repository itself (which was not the best idea and was the reason this was changed).

Meanwhile, the main branch of Vita3K ffmpeg's repository is only 1MB in size and it only needs to download around 10MB of prebuilts for the target system (git clone still downloads the old branch.., I'll move it to some other repository at some point).
I estimated that saving 200MB of internet bandwidth / disk space was worth squashing the git history.

**Comment by AniLeo** [comment]
> > > Why isn't this commit based on the vita3k/master branch?
> > 
> > 
> > Because the master branch squashed the entire git history, the `old` branch contains all the same commits but in an unsquashed manner. This is to avoid destroying git history and importing individual commits as is.
> 
> Hello, the reason I squashed the entire git history together is to decrease the repository size when cloning it. Right now if you do a `git clone https://github.com/RPCS3/ffmpeg-core.git`, the resulting repository size is around 250MB. This is because before the squash, the prebuilts for all the targets were in the repository itself (which was not the best idea and was the reason this was changed).
> 
> Meanwhile, the main branch of Vita3K ffmpeg's repository is only 1MB in size and it only needs to download around 10MB of prebuilts for the target system (git clone still downloads the old branch.., I'll move it to some other repository at some point). I estimated that saving 200MB of internet bandwidth / disk space was worth squashing the git history.

That makes sense, you can use `git clone --depth 1 https://github.com/RPCS3/ffmpeg-core.git` still, but then it will require initialising submodules as shallow when cloning the main repo itself

We're still keeping the libs for windows x64 on the repository because of our msvc setup

One question since you're here, is there any reason to be using ffmpeg5 over ffmpeg6 on your side?

**Comment by Macdu** [comment]
> > > > Why isn't this commit based on the vita3k/master branch?
> > > 
> > > 
> > > Because the master branch squashed the entire git history, the `old` branch contains all the same commits but in an unsquashed manner. This is to avoid destroying git history and importing individual commits as is.
> > 
> > 
> > Hello, the reason I squashed the entire git history together is to decrease the repository size when cloning it. Right now if you do a `git clone https://github.com/RPCS3/ffmpeg-core.git`, the resulting repository size is around 250MB. This is because before the squash, the prebuilts for all the targets were in the repository itself (which was not the best idea and was the reason this was changed).
> > Meanwhile, the main branch of Vita3K ffmpeg's repository is only 1MB in size and it only needs to download around 10MB of prebuilts for the target system (git clone still downloads the old branch.., I'll move it to some other repository at some point). I estimated that saving 200MB of internet bandwidth / disk space was worth squashing the git history.
> 
> That makes sense, you can use `git clone --depth 1 https://github.com/RPCS3/ffmpeg-core.git` still, but then it will require initialising submodules as shallow when cloning the main repo itself
> 
> We're still keeping the libs for windows x64 on the repository because of our msvc setup
> 
> One question since you're here, is there any reason to be using ffmpeg5 over ffmpeg6 on your side?

Not really, the only reason it is building ffmpeg5 is because vcpkg had not yet updated its ffmpeg package to 6 when I set it up.  There shouldn't be a reason not to be able to update to ffmpeg 7 on Vita3K's side.

**Pull request merged**
